	tilepal 0, GREEN, GREEN, GREEN, GREEN, GRAY, BROWN, GREEN, BROWN
	tilepal 0, BROWN, GRAY, RED, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, GREEN, GREEN, GREEN, GRAY, GRAY, GRAY, BROWN
	tilepal 0, BROWN, GRAY, RED, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, RED, RED, GRAY, GRAY, RED, RED, RED, RED
	tilepal 0, RED, RED, RED, RED, RED, GREEN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, WATER, WATER, BROWN
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, PRIORITY_GREEN, PRIORITY_GREEN, RED
	tilepal 0, RED, RED, RED, WATER, ROOF, WATER, WATER, ROOF
	tilepal 0, WATER, BROWN, BROWN, GRAY, GRAY, PRIORITY_GREEN, PRIORITY_GREEN, TEXT
	tilepal 0, RED, RED, RED, ROOF, WATER, ROOF, ROOF, WATER
	tilepal 0, ROOF
