	tilepal 0, WATER, RED, RED, GRAY, GRAY, PRIORITY_GRAY, PRIORITY_GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, BROWN, BROWN, RED, RED, PRIORITY_GRAY, PRIORITY_GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, BROWN, BROWN, RED, RED, GRAY, GRAY, GRAY
	tilepal 0, PRIORITY_GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER, ROOF
	tilepal 0, GRAY, RED, RED, RED, GRAY, GRAY, GRAY, GRAY
	tilepal 0, RED, RED, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, BROWN, RED, RED, RED, RED, GRAY, RED, RED
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, RED, RED, RED, RED, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY