	tilepal 0, WATER, GRAY, RED, RED, WATER, WATER, PRIORITY_GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, RED, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, RED, RED, WATER, WATER, GRAY, RED
	tilepal 0, WATER, WATER, GRAY, GRAY, RED, RED, GRAY, GRAY
	tilepal 0, PRIORITY_GREEN, PRIORITY_GREEN, BROWN, BROWN, RED, YELLOW, RED, RED
	tilepal 0, WATER, GRAY, RED, RED, WATER, WATER, WATER, WATER
	tilepal 0, PRIORITY_GREEN, PRIORITY_GREEN, BROWN, BROWN, RED, YELLOW, GRAY, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, YELLOW, YELLOW
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY