	tilepal 0, GRAY, WATER, WATER, WATER, BROWN, WATER, WATER, RED
	tilepal 0, RED, ROOF, ROOF, BROWN, ROOF, RED, RED, RED
	tilepal 0, ROOF, WATER, ROOF, WATER, ROOF, WATER, WATER, RED
	tilepal 0, RED, ROOF, ROOF, WATER, ROOF, RED, RED, RED
	tilepal 0, ROOF, ROOF, WATER, BROWN, RED, WATER, WATER, BROWN
	tilepal 0, BROWN, GRAY, GRAY, BROWN, ROOF, GRAY, GRAY, GRAY
	tilepal 0, ROOF, ROOF, WATER, WATER, RED, RED, BROWN, BROWN
	tilepal 0, BROWN, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, RED, RED, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, RED, BROWN, GRAY, GREEN, GREEN, ROOF, ROOF
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, RED, RED, GRAY, GRAY
	tilepal 0, RED, RED, GREEN, GREEN, ROOF, ROOF, GRAY, GRAY
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, TEXT
	tilepal 1, BROWN, BROWN, ROOF, GRAY, GRAY, BROWN, BROWN